// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: pkg/meta/pb/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid             string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Storage          string `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	StorageClass     string `protobuf:"bytes,4,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	Bucket           string `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey        string `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey        string `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SessionToken     string `protobuf:"bytes,8,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	BlockSize        int32  `protobuf:"varint,9,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Compression      string `protobuf:"bytes,10,opt,name=compression,proto3" json:"compression,omitempty"`
	Shards           int32  `protobuf:"varint,11,opt,name=shards,proto3" json:"shards,omitempty"`
	HashPrefix       bool   `protobuf:"varint,12,opt,name=hash_prefix,json=hashPrefix,proto3" json:"hash_prefix,omitempty"`
	Capacity         uint64 `protobuf:"varint,13,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Inodes           uint64 `protobuf:"varint,14,opt,name=inodes,proto3" json:"inodes,omitempty"`
	EncryptKey       string `protobuf:"bytes,15,opt,name=encrypt_key,json=encryptKey,proto3" json:"encrypt_key,omitempty"`
	EncryptAlgo      string `protobuf:"bytes,16,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	KeyEncrypted     bool   `protobuf:"varint,17,opt,name=key_encrypted,json=keyEncrypted,proto3" json:"key_encrypted,omitempty"`
	UploadLimit      int64  `protobuf:"varint,18,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`       // Mbps
	DownloadLimit    int64  `protobuf:"varint,19,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"` // Mbps
	TrashDays        int32  `protobuf:"varint,20,opt,name=trash_days,json=trashDays,proto3" json:"trash_days,omitempty"`
	MetaVersion      int32  `protobuf:"varint,21,opt,name=meta_version,json=metaVersion,proto3" json:"meta_version,omitempty"`
	MinClientVersion string `protobuf:"bytes,22,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version,omitempty"`
	MaxClientVersion string `protobuf:"bytes,23,opt,name=max_client_version,json=maxClientVersion,proto3" json:"max_client_version,omitempty"`
	DirStats         bool   `protobuf:"varint,24,opt,name=dir_stats,json=dirStats,proto3" json:"dir_stats,omitempty"`
	EnableAcl        bool   `protobuf:"varint,25,opt,name=enable_acl,json=enableAcl,proto3" json:"enable_acl,omitempty"`
}

func (x *Format) Reset() {
	*x = Format{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Format) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Format) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Format) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *Format) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *Format) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Format) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Format) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Format) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *Format) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *Format) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *Format) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *Format) GetHashPrefix() bool {
	if x != nil {
		return x.HashPrefix
	}
	return false
}

func (x *Format) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Format) GetInodes() uint64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

func (x *Format) GetEncryptKey() string {
	if x != nil {
		return x.EncryptKey
	}
	return ""
}

func (x *Format) GetEncryptAlgo() string {
	if x != nil {
		return x.EncryptAlgo
	}
	return ""
}

func (x *Format) GetKeyEncrypted() bool {
	if x != nil {
		return x.KeyEncrypted
	}
	return false
}

func (x *Format) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *Format) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

func (x *Format) GetTrashDays() int32 {
	if x != nil {
		return x.TrashDays
	}
	return 0
}

func (x *Format) GetMetaVersion() int32 {
	if x != nil {
		return x.MetaVersion
	}
	return 0
}

func (x *Format) GetMinClientVersion() string {
	if x != nil {
		return x.MinClientVersion
	}
	return ""
}

func (x *Format) GetMaxClientVersion() string {
	if x != nil {
		return x.MaxClientVersion
	}
	return ""
}

func (x *Format) GetDirStats() bool {
	if x != nil {
		return x.DirStats
	}
	return false
}

func (x *Format) GetEnableAcl() bool {
	if x != nil {
		return x.EnableAcl
	}
	return false
}

type Counters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsedSpace   int64 `protobuf:"varint,1,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	UsedInodes  int64 `protobuf:"varint,2,opt,name=usedInodes,proto3" json:"usedInodes,omitempty"`
	NextInode   int64 `protobuf:"varint,3,opt,name=nextInode,proto3" json:"nextInode,omitempty"`
	NextChunk   int64 `protobuf:"varint,4,opt,name=nextChunk,proto3" json:"nextChunk,omitempty"`
	NextSession int64 `protobuf:"varint,5,opt,name=nextSession,proto3" json:"nextSession,omitempty"`
	NextTrash   int64 `protobuf:"varint,6,opt,name=nextTrash,proto3" json:"nextTrash,omitempty"`
}

func (x *Counters) Reset() {
	*x = Counters{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counters) ProtoMessage() {}

func (x *Counters) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counters.ProtoReflect.Descriptor instead.
func (*Counters) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{1}
}

func (x *Counters) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *Counters) GetUsedInodes() int64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *Counters) GetNextInode() int64 {
	if x != nil {
		return x.NextInode
	}
	return 0
}

func (x *Counters) GetNextChunk() int64 {
	if x != nil {
		return x.NextChunk
	}
	return 0
}

func (x *Counters) GetNextSession() int64 {
	if x != nil {
		return x.NextSession
	}
	return 0
}

func (x *Counters) GetNextTrash() int64 {
	if x != nil {
		return x.NextTrash
	}
	return 0
}

type Sustained struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid    uint64   `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Inodes []uint64 `protobuf:"varint,2,rep,packed,name=inodes,proto3" json:"inodes,omitempty"`
}

func (x *Sustained) Reset() {
	*x = Sustained{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sustained) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sustained) ProtoMessage() {}

func (x *Sustained) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sustained.ProtoReflect.Descriptor instead.
func (*Sustained) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{2}
}

func (x *Sustained) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *Sustained) GetInodes() []uint64 {
	if x != nil {
		return x.Inodes
	}
	return nil
}

type SustainedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Sustained `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SustainedList) Reset() {
	*x = SustainedList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SustainedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SustainedList) ProtoMessage() {}

func (x *SustainedList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SustainedList.ProtoReflect.Descriptor instead.
func (*SustainedList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{3}
}

func (x *SustainedList) GetList() []*Sustained {
	if x != nil {
		return x.List
	}
	return nil
}

type DelFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode  uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Length uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Expire int64  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *DelFile) Reset() {
	*x = DelFile{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFile) ProtoMessage() {}

func (x *DelFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFile.ProtoReflect.Descriptor instead.
func (*DelFile) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{4}
}

func (x *DelFile) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *DelFile) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DelFile) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type DelFileList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DelFile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DelFileList) Reset() {
	*x = DelFileList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFileList) ProtoMessage() {}

func (x *DelFileList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFileList.ProtoReflect.Descriptor instead.
func (*DelFileList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{5}
}

func (x *DelFileList) GetList() []*DelFile {
	if x != nil {
		return x.List
	}
	return nil
}

type SliceRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Refs int64  `protobuf:"varint,3,opt,name=refs,proto3" json:"refs,omitempty"`
}

func (x *SliceRef) Reset() {
	*x = SliceRef{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceRef) ProtoMessage() {}

func (x *SliceRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceRef.ProtoReflect.Descriptor instead.
func (*SliceRef) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{6}
}

func (x *SliceRef) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SliceRef) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SliceRef) GetRefs() int64 {
	if x != nil {
		return x.Refs
	}
	return 0
}

type SliceRefList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SliceRef `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SliceRefList) Reset() {
	*x = SliceRefList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceRefList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceRefList) ProtoMessage() {}

func (x *SliceRefList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceRefList.ProtoReflect.Descriptor instead.
func (*SliceRefList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{7}
}

func (x *SliceRefList) GetList() []*SliceRef {
	if x != nil {
		return x.List
	}
	return nil
}

type AclEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Perm uint32 `protobuf:"varint,2,opt,name=perm,proto3" json:"perm,omitempty"`
}

func (x *AclEntry) Reset() {
	*x = AclEntry{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclEntry) ProtoMessage() {}

func (x *AclEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclEntry.ProtoReflect.Descriptor instead.
func (*AclEntry) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{8}
}

func (x *AclEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AclEntry) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type Acl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner  uint32      `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Group  uint32      `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	Other  uint32      `protobuf:"varint,4,opt,name=other,proto3" json:"other,omitempty"`
	Mask   uint32      `protobuf:"varint,5,opt,name=mask,proto3" json:"mask,omitempty"`
	Users  []*AclEntry `protobuf:"bytes,6,rep,name=users,proto3" json:"users,omitempty"`
	Groups []*AclEntry `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Acl) Reset() {
	*x = Acl{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acl) ProtoMessage() {}

func (x *Acl) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acl.ProtoReflect.Descriptor instead.
func (*Acl) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{9}
}

func (x *Acl) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Acl) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Acl) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Acl) GetOther() uint32 {
	if x != nil {
		return x.Other
	}
	return 0
}

func (x *Acl) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *Acl) GetUsers() []*AclEntry {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Acl) GetGroups() []*AclEntry {
	if x != nil {
		return x.Groups
	}
	return nil
}

type AclList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Acl `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AclList) Reset() {
	*x = AclList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclList) ProtoMessage() {}

func (x *AclList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclList.ProtoReflect.Descriptor instead.
func (*AclList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{10}
}

func (x *AclList) GetList() []*Acl {
	if x != nil {
		return x.List
	}
	return nil
}

type Xattr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Xattr) Reset() {
	*x = Xattr{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xattr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xattr) ProtoMessage() {}

func (x *Xattr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xattr.ProtoReflect.Descriptor instead.
func (*Xattr) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{11}
}

func (x *Xattr) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Xattr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Xattr) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type XattrList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Xattr `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *XattrList) Reset() {
	*x = XattrList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XattrList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XattrList) ProtoMessage() {}

func (x *XattrList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XattrList.ProtoReflect.Descriptor instead.
func (*XattrList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{12}
}

func (x *XattrList) GetList() []*Xattr {
	if x != nil {
		return x.List
	}
	return nil
}

type Quota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode      uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	MaxSpace   int64  `protobuf:"varint,2,opt,name=maxSpace,proto3" json:"maxSpace,omitempty"`
	MaxInodes  int64  `protobuf:"varint,3,opt,name=maxInodes,proto3" json:"maxInodes,omitempty"`
	UsedSpace  int64  `protobuf:"varint,4,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	UsedInodes int64  `protobuf:"varint,5,opt,name=usedInodes,proto3" json:"usedInodes,omitempty"`
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{13}
}

func (x *Quota) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Quota) GetMaxSpace() int64 {
	if x != nil {
		return x.MaxSpace
	}
	return 0
}

func (x *Quota) GetMaxInodes() int64 {
	if x != nil {
		return x.MaxInodes
	}
	return 0
}

func (x *Quota) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *Quota) GetUsedInodes() int64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

type QuotaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Quota `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *QuotaList) Reset() {
	*x = QuotaList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaList) ProtoMessage() {}

func (x *QuotaList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaList.ProtoReflect.Descriptor instead.
func (*QuotaList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{14}
}

func (x *QuotaList) GetList() []*Quota {
	if x != nil {
		return x.List
	}
	return nil
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode      uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	DataLength int64  `protobuf:"varint,2,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	UsedSpace  int64  `protobuf:"varint,3,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	UsedInodes int64  `protobuf:"varint,4,opt,name=usedInodes,proto3" json:"usedInodes,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{15}
}

func (x *Stat) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Stat) GetDataLength() int64 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

func (x *Stat) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *Stat) GetUsedInodes() int64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

type StatList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Stat `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StatList) Reset() {
	*x = StatList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatList) ProtoMessage() {}

func (x *StatList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatList.ProtoReflect.Descriptor instead.
func (*StatList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{16}
}

func (x *StatList) GetList() []*Stat {
	if x != nil {
		return x.List
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent uint64 `protobuf:"varint,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Inode  uint64 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Name   []byte `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type   uint32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{17}
}

func (x *Edge) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *Edge) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Edge) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Edge) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type EdgeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Edge `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *EdgeList) Reset() {
	*x = EdgeList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeList) ProtoMessage() {}

func (x *EdgeList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeList.ProtoReflect.Descriptor instead.
func (*EdgeList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{18}
}

func (x *EdgeList) GetList() []*Edge {
	if x != nil {
		return x.List
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode        uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Type         uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Flags        uint32 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode         uint32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid          uint32 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid          uint32 `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	Atime        int64  `protobuf:"varint,7,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime        int64  `protobuf:"varint,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime        int64  `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime,omitempty"`
	AtimeNsec    int32  `protobuf:"varint,10,opt,name=atime_nsec,json=atimeNsec,proto3" json:"atime_nsec,omitempty"`
	MtimeNsec    int32  `protobuf:"varint,11,opt,name=mtime_nsec,json=mtimeNsec,proto3" json:"mtime_nsec,omitempty"`
	CtimeNsec    int32  `protobuf:"varint,12,opt,name=ctime_nsec,json=ctimeNsec,proto3" json:"ctime_nsec,omitempty"`
	Nlink        uint32 `protobuf:"varint,13,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Length       uint64 `protobuf:"varint,14,opt,name=length,proto3" json:"length,omitempty"`
	Rdev         uint32 `protobuf:"varint,15,opt,name=rdev,proto3" json:"rdev,omitempty"`
	Parent       uint64 `protobuf:"varint,16,opt,name=parent,proto3" json:"parent,omitempty"`
	AccessAclId  uint32 `protobuf:"varint,17,opt,name=access_acl_id,json=accessAclId,proto3" json:"access_acl_id,omitempty"`
	DefaultAclId uint32 `protobuf:"varint,18,opt,name=default_acl_id,json=defaultAclId,proto3" json:"default_acl_id,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{19}
}

func (x *Node) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Node) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Node) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Node) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Node) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Node) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Node) GetAtime() int64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *Node) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Node) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Node) GetAtimeNsec() int32 {
	if x != nil {
		return x.AtimeNsec
	}
	return 0
}

func (x *Node) GetMtimeNsec() int32 {
	if x != nil {
		return x.MtimeNsec
	}
	return 0
}

func (x *Node) GetCtimeNsec() int32 {
	if x != nil {
		return x.CtimeNsec
	}
	return 0
}

func (x *Node) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Node) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Node) GetRdev() uint32 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *Node) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *Node) GetAccessAclId() uint32 {
	if x != nil {
		return x.AccessAclId
	}
	return 0
}

func (x *Node) GetDefaultAclId() uint32 {
	if x != nil {
		return x.DefaultAclId
	}
	return 0
}

type NodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Node `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{20}
}

func (x *NodeList) GetList() []*Node {
	if x != nil {
		return x.List
	}
	return nil
}

type Slice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos  uint32 `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Off  uint32 `protobuf:"varint,4,opt,name=off,proto3" json:"off,omitempty"`
	Len  uint32 `protobuf:"varint,5,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{21}
}

func (x *Slice) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Slice) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *Slice) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Slice) GetOff() uint32 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *Slice) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode  uint64   `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Index  uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Slices []*Slice `protobuf:"bytes,3,rep,name=slices,proto3" json:"slices,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{22}
}

func (x *Chunk) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Chunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetSlices() []*Slice {
	if x != nil {
		return x.Slices
	}
	return nil
}

type ChunkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Chunk `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ChunkList) Reset() {
	*x = ChunkList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkList) ProtoMessage() {}

func (x *ChunkList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkList.ProtoReflect.Descriptor instead.
func (*ChunkList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{23}
}

func (x *ChunkList) GetList() []*Chunk {
	if x != nil {
		return x.List
	}
	return nil
}

type Symlink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode  uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Target []byte `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Symlink) Reset() {
	*x = Symlink{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symlink) ProtoMessage() {}

func (x *Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symlink.ProtoReflect.Descriptor instead.
func (*Symlink) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{24}
}

func (x *Symlink) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Symlink) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

type SymlinkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Symlink `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SymlinkList) Reset() {
	*x = SymlinkList{}
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkList) ProtoMessage() {}

func (x *SymlinkList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_backup_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkList.ProtoReflect.Descriptor instead.
func (*SymlinkList) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_backup_proto_rawDescGZIP(), []int{25}
}

func (x *SymlinkList) GetList() []*Symlink {
	if x != nil {
		return x.List
	}
	return nil
}

var File_pkg_meta_pb_backup_proto protoreflect.FileDescriptor

var file_pkg_meta_pb_backup_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa5,
	0x06, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x12, 0x23, 0x0a,
	0x0d, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x11,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x72, 0x61, 0x73, 0x68, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x74, 0x72, 0x61, 0x73, 0x68, 0x44, 0x61, 0x79, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x15, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c,
	0x0a, 0x12, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x69, 0x6e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12,
	0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x61, 0x78, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x18, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x69, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x61, 0x63, 0x6c, 0x18, 0x19, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x63, 0x6c, 0x22, 0xc4, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x20, 0x0a,
	0x0b, 0x6e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x72, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x72, 0x61, 0x73, 0x68, 0x22, 0x35, 0x0a,
	0x09, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x69, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x0d, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x64, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x2e, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x08, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x66,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x66, 0x73, 0x22, 0x30, 0x0a,
	0x0c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x66, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x2e, 0x0a, 0x08, 0x41, 0x63, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x65, 0x72, 0x6d, 0x22,
	0xb5, 0x01, 0x0a, 0x03, 0x41, 0x63, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x63, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x24, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x26, 0x0a, 0x07, 0x41, 0x63, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x47, 0x0a, 0x05, 0x58, 0x61, 0x74, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x09, 0x58, 0x61, 0x74, 0x74,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x58, 0x61, 0x74, 0x74, 0x72, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x09,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x7a, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5c,
	0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x08,
	0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x67, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xc1, 0x03, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61,
	0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x74,
	0x69, 0x6d, 0x65, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x74, 0x69,
	0x6d, 0x65, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x64, 0x65, 0x76, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x72, 0x64, 0x65, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x61, 0x63, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41,
	0x63, 0x6c, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x63, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x63, 0x6c, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x66, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6f, 0x66, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x22, 0x56, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x21, 0x0a, 0x06,
	0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x2a, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x07, 0x53,
	0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x0b, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_meta_pb_backup_proto_rawDescOnce sync.Once
	file_pkg_meta_pb_backup_proto_rawDescData = file_pkg_meta_pb_backup_proto_rawDesc
)

func file_pkg_meta_pb_backup_proto_rawDescGZIP() []byte {
	file_pkg_meta_pb_backup_proto_rawDescOnce.Do(func() {
		file_pkg_meta_pb_backup_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_meta_pb_backup_proto_rawDescData)
	})
	return file_pkg_meta_pb_backup_proto_rawDescData
}

var file_pkg_meta_pb_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pkg_meta_pb_backup_proto_goTypes = []any{
	(*Format)(nil),        // 0: pb.Format
	(*Counters)(nil),      // 1: pb.Counters
	(*Sustained)(nil),     // 2: pb.Sustained
	(*SustainedList)(nil), // 3: pb.SustainedList
	(*DelFile)(nil),       // 4: pb.DelFile
	(*DelFileList)(nil),   // 5: pb.DelFileList
	(*SliceRef)(nil),      // 6: pb.SliceRef
	(*SliceRefList)(nil),  // 7: pb.SliceRefList
	(*AclEntry)(nil),      // 8: pb.AclEntry
	(*Acl)(nil),           // 9: pb.Acl
	(*AclList)(nil),       // 10: pb.AclList
	(*Xattr)(nil),         // 11: pb.Xattr
	(*XattrList)(nil),     // 12: pb.XattrList
	(*Quota)(nil),         // 13: pb.Quota
	(*QuotaList)(nil),     // 14: pb.QuotaList
	(*Stat)(nil),          // 15: pb.Stat
	(*StatList)(nil),      // 16: pb.StatList
	(*Edge)(nil),          // 17: pb.Edge
	(*EdgeList)(nil),      // 18: pb.EdgeList
	(*Node)(nil),          // 19: pb.Node
	(*NodeList)(nil),      // 20: pb.NodeList
	(*Slice)(nil),         // 21: pb.Slice
	(*Chunk)(nil),         // 22: pb.Chunk
	(*ChunkList)(nil),     // 23: pb.ChunkList
	(*Symlink)(nil),       // 24: pb.Symlink
	(*SymlinkList)(nil),   // 25: pb.SymlinkList
}
var file_pkg_meta_pb_backup_proto_depIdxs = []int32{
	2,  // 0: pb.SustainedList.list:type_name -> pb.Sustained
	4,  // 1: pb.DelFileList.list:type_name -> pb.DelFile
	6,  // 2: pb.SliceRefList.list:type_name -> pb.SliceRef
	8,  // 3: pb.Acl.users:type_name -> pb.AclEntry
	8,  // 4: pb.Acl.groups:type_name -> pb.AclEntry
	9,  // 5: pb.AclList.list:type_name -> pb.Acl
	11, // 6: pb.XattrList.list:type_name -> pb.Xattr
	13, // 7: pb.QuotaList.list:type_name -> pb.Quota
	15, // 8: pb.StatList.list:type_name -> pb.Stat
	17, // 9: pb.EdgeList.list:type_name -> pb.Edge
	19, // 10: pb.NodeList.list:type_name -> pb.Node
	21, // 11: pb.Chunk.slices:type_name -> pb.Slice
	22, // 12: pb.ChunkList.list:type_name -> pb.Chunk
	24, // 13: pb.SymlinkList.list:type_name -> pb.Symlink
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_meta_pb_backup_proto_init() }
func file_pkg_meta_pb_backup_proto_init() {
	if File_pkg_meta_pb_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_meta_pb_backup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_meta_pb_backup_proto_goTypes,
		DependencyIndexes: file_pkg_meta_pb_backup_proto_depIdxs,
		MessageInfos:      file_pkg_meta_pb_backup_proto_msgTypes,
	}.Build()
	File_pkg_meta_pb_backup_proto = out.File
	file_pkg_meta_pb_backup_proto_rawDesc = nil
	file_pkg_meta_pb_backup_proto_goTypes = nil
	file_pkg_meta_pb_backup_proto_depIdxs = nil
}
