// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: file2.proto

package file2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The deferred encoding is used to place the encoding itself in a different
// part of the file.  This is most commonly used to allow encodings to be shared
// across different columns.  For example, when writing a file with thousands of
// columns, where many pages have the exact same encoding, it can be useful
// to cut down on the size of the metadata by using a deferred encoding.
type DeferredEncoding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Location of the buffer containing the encoding.
	//
	//   - If sharing encodings across columns then this will be in a global buffer
	//   - If sharing encodings across pages within a column this could be in a
	//     column metadata buffer.
	//   - This could also be a page buffer if the encoding is not shared, needs
	//     to be written before the file ends, and the encoding is too large to load
	//     unless we first determine the page needs to be read.  This combination
	//     seems unusual.
	BufferLocation uint64 `protobuf:"varint,1,opt,name=buffer_location,json=bufferLocation,proto3" json:"buffer_location,omitempty"`
	BufferLength   uint64 `protobuf:"varint,2,opt,name=buffer_length,json=bufferLength,proto3" json:"buffer_length,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeferredEncoding) Reset() {
	*x = DeferredEncoding{}
	mi := &file_file2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeferredEncoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeferredEncoding) ProtoMessage() {}

func (x *DeferredEncoding) ProtoReflect() protoreflect.Message {
	mi := &file_file2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeferredEncoding.ProtoReflect.Descriptor instead.
func (*DeferredEncoding) Descriptor() ([]byte, []int) {
	return file_file2_proto_rawDescGZIP(), []int{0}
}

func (x *DeferredEncoding) GetBufferLocation() uint64 {
	if x != nil {
		return x.BufferLocation
	}
	return 0
}

func (x *DeferredEncoding) GetBufferLength() uint64 {
	if x != nil {
		return x.BufferLength
	}
	return 0
}

// The encoding is placed directly in the metadata section
type DirectEncoding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bytes that make up the encoding embedded directly in the metadata
	//
	// This is the most common approach.
	Encoding      []byte `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectEncoding) Reset() {
	*x = DirectEncoding{}
	mi := &file_file2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectEncoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectEncoding) ProtoMessage() {}

func (x *DirectEncoding) ProtoReflect() protoreflect.Message {
	mi := &file_file2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectEncoding.ProtoReflect.Descriptor instead.
func (*DirectEncoding) Descriptor() ([]byte, []int) {
	return file_file2_proto_rawDescGZIP(), []int{1}
}

func (x *DirectEncoding) GetEncoding() []byte {
	if x != nil {
		return x.Encoding
	}
	return nil
}

// An encoding stores the information needed to decode a column or page
//
// For example, it could describe if the page is using bit packing, and how many bits
// there are in each individual value.
//
// At the column level it can be used to wrap columns with dictionaries or statistics.
type Encoding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*Encoding_Indirect
	//	*Encoding_Direct
	//	*Encoding_None
	Location      isEncoding_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Encoding) Reset() {
	*x = Encoding{}
	mi := &file_file2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Encoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encoding) ProtoMessage() {}

func (x *Encoding) ProtoReflect() protoreflect.Message {
	mi := &file_file2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encoding.ProtoReflect.Descriptor instead.
func (*Encoding) Descriptor() ([]byte, []int) {
	return file_file2_proto_rawDescGZIP(), []int{2}
}

func (x *Encoding) GetLocation() isEncoding_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Encoding) GetIndirect() *DeferredEncoding {
	if x != nil {
		if x, ok := x.Location.(*Encoding_Indirect); ok {
			return x.Indirect
		}
	}
	return nil
}

func (x *Encoding) GetDirect() *DirectEncoding {
	if x != nil {
		if x, ok := x.Location.(*Encoding_Direct); ok {
			return x.Direct
		}
	}
	return nil
}

func (x *Encoding) GetNone() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Location.(*Encoding_None); ok {
			return x.None
		}
	}
	return nil
}

type isEncoding_Location interface {
	isEncoding_Location()
}

type Encoding_Indirect struct {
	// The encoding is stored elsewhere and not part of this protobuf message
	Indirect *DeferredEncoding `protobuf:"bytes,1,opt,name=indirect,proto3,oneof"`
}

type Encoding_Direct struct {
	// The encoding is stored within this protobuf message
	Direct *DirectEncoding `protobuf:"bytes,2,opt,name=direct,proto3,oneof"`
}

type Encoding_None struct {
	// There is no encoding information
	None *emptypb.Empty `protobuf:"bytes,3,opt,name=none,proto3,oneof"`
}

func (*Encoding_Indirect) isEncoding_Location() {}

func (*Encoding_Direct) isEncoding_Location() {}

func (*Encoding_None) isEncoding_Location() {}

// Each column has a metadata block that is placed at the end of the file.
// These may be read individually to allow for column projection.
type ColumnMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoding information about the column itself.  This typically describes
	// how to interpret the column metadata buffers.  For example, it could
	// describe how statistics or dictionaries are stored in the column metadata.
	Encoding *Encoding `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// The pages in the column
	Pages []*ColumnMetadata_Page `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	// The file offsets of each of the column metadata buffers
	//
	// There may be zero buffers.
	BufferOffsets []uint64 `protobuf:"varint,3,rep,packed,name=buffer_offsets,json=bufferOffsets,proto3" json:"buffer_offsets,omitempty"`
	// The size (in bytes) of each of the column metadata buffers
	//
	// This field will have the same length as `buffer_offsets` and
	// may be empty.
	BufferSizes   []uint64 `protobuf:"varint,4,rep,packed,name=buffer_sizes,json=bufferSizes,proto3" json:"buffer_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMetadata) Reset() {
	*x = ColumnMetadata{}
	mi := &file_file2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata) ProtoMessage() {}

func (x *ColumnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata.ProtoReflect.Descriptor instead.
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return file_file2_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnMetadata) GetEncoding() *Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *ColumnMetadata) GetPages() []*ColumnMetadata_Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *ColumnMetadata) GetBufferOffsets() []uint64 {
	if x != nil {
		return x.BufferOffsets
	}
	return nil
}

func (x *ColumnMetadata) GetBufferSizes() []uint64 {
	if x != nil {
		return x.BufferSizes
	}
	return nil
}

// This describes a page of column data.
type ColumnMetadata_Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file offsets for each of the page buffers
	//
	// The number of buffers is variable and depends on the encoding.  There
	// may be zero buffers (e.g. constant encoded data) in which case this
	// could be empty.
	BufferOffsets []uint64 `protobuf:"varint,1,rep,packed,name=buffer_offsets,json=bufferOffsets,proto3" json:"buffer_offsets,omitempty"`
	// The size (in bytes) of each of the page buffers
	//
	// This field will have the same length as `buffer_offsets` and
	// may be empty.
	BufferSizes []uint64 `protobuf:"varint,2,rep,packed,name=buffer_sizes,json=bufferSizes,proto3" json:"buffer_sizes,omitempty"`
	// Logical length (e.g. # rows) of the page
	Length uint64 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	// The encoding used to encode the page
	Encoding *Encoding `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// The priority of the page
	//
	// For tabular data this will be the top-level row number of the first row
	// in the page (and top-level rows should not split across pages).
	Priority      uint64 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMetadata_Page) Reset() {
	*x = ColumnMetadata_Page{}
	mi := &file_file2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMetadata_Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata_Page) ProtoMessage() {}

func (x *ColumnMetadata_Page) ProtoReflect() protoreflect.Message {
	mi := &file_file2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata_Page.ProtoReflect.Descriptor instead.
func (*ColumnMetadata_Page) Descriptor() ([]byte, []int) {
	return file_file2_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ColumnMetadata_Page) GetBufferOffsets() []uint64 {
	if x != nil {
		return x.BufferOffsets
	}
	return nil
}

func (x *ColumnMetadata_Page) GetBufferSizes() []uint64 {
	if x != nil {
		return x.BufferSizes
	}
	return nil
}

func (x *ColumnMetadata_Page) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ColumnMetadata_Page) GetEncoding() *Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *ColumnMetadata_Page) GetPriority() uint64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_file2_proto protoreflect.FileDescriptor

const file_file2_proto_rawDesc = "" +
	"\n" +
	"\vfile2.proto\x12\rlance.file.v2\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x10DeferredEncoding\x12'\n" +
	"\x0fbuffer_location\x18\x01 \x01(\x04R\x0ebufferLocation\x12#\n" +
	"\rbuffer_length\x18\x02 \x01(\x04R\fbufferLength\",\n" +
	"\x0eDirectEncoding\x12\x1a\n" +
	"\bencoding\x18\x01 \x01(\fR\bencoding\"\xbc\x01\n" +
	"\bEncoding\x12=\n" +
	"\bindirect\x18\x01 \x01(\v2\x1f.lance.file.v2.DeferredEncodingH\x00R\bindirect\x127\n" +
	"\x06direct\x18\x02 \x01(\v2\x1d.lance.file.v2.DirectEncodingH\x00R\x06direct\x12,\n" +
	"\x04none\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x04noneB\n" +
	"\n" +
	"\blocation\"\x85\x03\n" +
	"\x0eColumnMetadata\x123\n" +
	"\bencoding\x18\x01 \x01(\v2\x17.lance.file.v2.EncodingR\bencoding\x128\n" +
	"\x05pages\x18\x02 \x03(\v2\".lance.file.v2.ColumnMetadata.PageR\x05pages\x12%\n" +
	"\x0ebuffer_offsets\x18\x03 \x03(\x04R\rbufferOffsets\x12!\n" +
	"\fbuffer_sizes\x18\x04 \x03(\x04R\vbufferSizes\x1a\xb9\x01\n" +
	"\x04Page\x12%\n" +
	"\x0ebuffer_offsets\x18\x01 \x03(\x04R\rbufferOffsets\x12!\n" +
	"\fbuffer_sizes\x18\x02 \x03(\x04R\vbufferSizes\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x123\n" +
	"\bencoding\x18\x04 \x01(\v2\x17.lance.file.v2.EncodingR\bencoding\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x04R\bpriorityb\x06proto3"

var (
	file_file2_proto_rawDescOnce sync.Once
	file_file2_proto_rawDescData []byte
)

func file_file2_proto_rawDescGZIP() []byte {
	file_file2_proto_rawDescOnce.Do(func() {
		file_file2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file2_proto_rawDesc), len(file_file2_proto_rawDesc)))
	})
	return file_file2_proto_rawDescData
}

var file_file2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_file2_proto_goTypes = []any{
	(*DeferredEncoding)(nil),    // 0: lance.file.v2.DeferredEncoding
	(*DirectEncoding)(nil),      // 1: lance.file.v2.DirectEncoding
	(*Encoding)(nil),            // 2: lance.file.v2.Encoding
	(*ColumnMetadata)(nil),      // 3: lance.file.v2.ColumnMetadata
	(*ColumnMetadata_Page)(nil), // 4: lance.file.v2.ColumnMetadata.Page
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_file2_proto_depIdxs = []int32{
	0, // 0: lance.file.v2.Encoding.indirect:type_name -> lance.file.v2.DeferredEncoding
	1, // 1: lance.file.v2.Encoding.direct:type_name -> lance.file.v2.DirectEncoding
	5, // 2: lance.file.v2.Encoding.none:type_name -> google.protobuf.Empty
	2, // 3: lance.file.v2.ColumnMetadata.encoding:type_name -> lance.file.v2.Encoding
	4, // 4: lance.file.v2.ColumnMetadata.pages:type_name -> lance.file.v2.ColumnMetadata.Page
	2, // 5: lance.file.v2.ColumnMetadata.Page.encoding:type_name -> lance.file.v2.Encoding
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_file2_proto_init() }
func file_file2_proto_init() {
	if File_file2_proto != nil {
		return
	}
	file_file2_proto_msgTypes[2].OneofWrappers = []any{
		(*Encoding_Indirect)(nil),
		(*Encoding_Direct)(nil),
		(*Encoding_None)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file2_proto_rawDesc), len(file_file2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file2_proto_goTypes,
		DependencyIndexes: file_file2_proto_depIdxs,
		MessageInfos:      file_file2_proto_msgTypes,
	}.Build()
	File_file2_proto = out.File
	file_file2_proto_goTypes = nil
	file_file2_proto_depIdxs = nil
}
