name: 'upload_coverage_report'
description: 'upload coverage report of one job'
inputs:
  UPLOAD_TOKEN:
    description: 'upload token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: umount juicefs
      shell: bash
      run: |
        sudo umount /tmp/jfs || true
        sleep 3s

    - name: get job id
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
        job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | select(.status=="in_progress") | .id')
        echo Job ID is: ${job_id}
        echo "job_id=$job_id" >> $GITHUB_ENV

    - name: generate mount coverage report
      shell: bash
      run: |
        echo "generate coverage percentage report"
        sudo go tool covdata percent -i=cover/ | sudo tee cover/percent.txt
        echo "generate coverage text report"
        sudo go tool covdata textfmt -i=cover/ -o cover/cover.txt
        echo "generate coverage html report"
        sudo go tool cover -html=cover/cover.txt -o cover/cover.html
        [[ -z "${{inputs.UPLOAD_TOKEN}}" ]] && echo "no upload token, skip upload" && exit 0 || true
        .github/scripts/upload_coverage_report.sh cover/cover.html juicefs_${{github.workflow}}_${{github.run_id}}_${job_id}.html ${{inputs.UPLOAD_TOKEN}}
        