/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/juicedata/juicefs/sdk/java/libjfs */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 19 "main.go"


 #include <unistd.h>
 #include <inttypes.h>
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <fcntl.h>
 #include <utime.h>
 #include <stdlib.h>
 void jfs_callback(const char *msg);

#include <inttypes.h>

typedef struct {
	uint64_t inode;
	uint32_t mode;
	uint32_t uid;
	uint32_t gid;
	uint32_t atime;
	uint32_t mtime;
	uint32_t ctime;
	uint32_t nlink;
	uint64_t length;
} fileInfo;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void jfs_set_logger(void* cb);
extern GoInt64 jfs_init(GoUintptr credentialPtr, GoInt32 count, char* cname, char* cjsonConf, char* cuser, char* group, char* superuser, char* supergroup);
extern void jfs_update_uid_grouping(char* cname, char* uidstr, char* grouping);
extern GoInt32 jfs_getGroups(char* cname, char* cuser, GoUintptr buf, GoInt32 count);
extern GoInt32 jfs_term(GoInt64 pid, GoInt64 h);
extern GoInt32 jfs_open(GoInt64 pid, GoInt64 h, char* cpath, GoUintptr lenPtr, GoInt32 flags);
extern GoInt32 jfs_open_posix(GoInt64 pid, GoInt64 h, char* cpath, GoUintptr lenPtr, GoInt32 flags);
extern GoInt32 jfs_access(GoInt64 pid, GoInt64 h, char* cpath, GoInt64 flags);
extern GoInt32 jfs_create(GoInt64 pid, GoInt64 h, char* cpath, GoUint16 mode, GoUint16 umask);
extern GoInt32 jfs_mkdir(GoInt64 pid, GoInt64 h, char* cpath, GoUint16 mode, GoUint16 umask);
extern GoInt32 jfs_mkdirAll(GoInt64 pid, GoInt64 h, char* cpath, GoUint16 mode, GoUint16 umask, GoUint8 existOK);
extern GoInt32 jfs_delete(GoInt64 pid, GoInt64 h, char* cpath);
extern GoInt32 jfs_unlink(GoInt64 pid, GoInt64 h, char* cpath);
extern GoInt32 jfs_rmdir(GoInt64 pid, GoInt64 h, char* cpath);
extern GoInt32 jfs_rmr(GoInt64 pid, GoInt64 h, char* cpath);
extern GoInt32 jfs_rename(GoInt64 pid, GoInt64 h, char* oldpath, char* newpath);
extern GoInt32 jfs_rename0(GoInt64 pid, GoInt64 h, char* oldpath, char* newpath, GoUint32 flags);
extern GoInt32 jfs_truncate(GoInt64 pid, GoInt64 h, char* path, GoUint64 length);
extern GoInt32 jfs_setXattr(GoInt64 pid, GoInt64 h, char* path, char* name, GoUintptr value, GoInt32 vlen, GoInt32 mode);
extern GoInt32 jfs_setXattr2(GoInt64 pid, GoInt64 h, char* path, char* name, char* value, GoInt64 mode);
extern GoInt32 jfs_getXattr(GoInt64 pid, GoInt64 h, char* path, char* name, GoUintptr buf, GoInt32 bufsize);
extern GoInt32 jfs_getXattr2(GoInt64 pid, GoInt64 h, char* path, char* name, char** value);
extern GoInt32 jfs_listXattr(GoInt64 pid, GoInt64 h, char* path, GoUintptr buf, GoInt32 bufsize);
extern GoInt32 jfs_listXattr2(GoInt64 pid, GoInt64 h, char* path, char** value, GoInt* size);
extern GoInt32 jfs_removeXattr(GoInt64 pid, GoInt64 h, char* path, char* name);
extern GoInt32 jfs_getfacl(GoInt64 pid, GoInt64 h, char* path, GoInt32 acltype, GoUintptr buf, GoInt32 blen);
extern GoInt32 jfs_setfacl(GoInt64 pid, GoInt64 h, char* path, GoInt32 acltype, GoUintptr buf, GoInt32 alen);
extern GoInt32 jfs_link(GoInt64 pid, GoInt64 h, char* src, char* dst);
extern GoInt32 jfs_symlink(GoInt64 pid, GoInt64 h, char* target_, char* link_);
extern GoInt32 jfs_readlink(GoInt64 pid, GoInt64 h, char* link, GoUintptr buf, GoInt32 bufsize);
extern GoInt32 jfs_stat1(GoInt64 pid, GoInt64 h, char* cpath, GoUintptr buf);
extern GoInt32 jfs_lstat1(GoInt64 pid, GoInt64 h, char* cpath, GoUintptr buf);
extern GoInt32 jfs_stat(GoInt64 pid, GoInt64 h, char* cpath, fileInfo* info);
extern GoInt32 jfs_lstat(GoInt64 pid, GoInt64 h, char* cpath, fileInfo* info);
extern GoInt32 jfs_summary(GoInt64 pid, GoInt64 h, char* cpath, GoUintptr buf);
extern GoInt32 jfs_info(GoInt64 pid, GoInt64 h, char* cpath, GoUint8** p_buf, GoUint8 recursive, GoUint8 strict);
extern GoInt32 jfs_gettreesummary(GoInt64 pid, GoInt64 h, char* cpath, GoUint8 depth, GoUint8 entries, GoUint8** p_buf);
extern GoInt32 jfs_quota(GoInt64 pid, GoInt64 h, char* cpath, GoUint8 cmd, GoUint64 cap, GoUint64 inodes, GoUint8 strict, GoUint8 repair, GoUint8 create, GoUint8** p_buf);
extern GoInt32 jfs_statvfs(GoInt64 pid, GoInt64 h, GoUintptr buf);
extern GoInt32 jfs_chmod(GoInt64 pid, GoInt64 h, char* cpath, mode_t mode);
extern GoInt32 jfs_chown(GoInt64 pid, GoInt64 h, char* cpath, GoUint32 uid, GoUint32 gid);
extern GoInt32 jfs_utime(GoInt64 pid, GoInt64 h, char* cpath, GoInt64 mtime, GoInt64 atime);
extern GoInt32 jfs_setOwner(GoInt64 pid, GoInt64 h, char* cpath, char* owner, char* group);
extern GoInt32 jfs_listdir(GoInt64 pid, GoInt64 h, char* cpath, GoInt64 offset, GoUintptr buf, GoInt32 bufsize);
extern GoInt32 jfs_listdir2(GoInt64 pid, GoInt64 h, char* cpath, GoUint8 plus, GoUint8** buf, GoInt64* size);
extern GoInt32 jfs_concat(GoInt64 pid, GoInt64 h, char* _dst, GoUintptr buf, GoInt32 bufsize);
extern GoInt32 jfs_clone(GoInt64 pid, GoInt64 h, char* _src, char* _dst, GoUint8 preserve);
extern GoInt32 jfs_status(GoInt64 pid, GoInt64 h, GoUint8 trash, GoUint64 session, GoUint8** p_buf);
extern GoInt64 jfs_lseek(GoInt64 pid, GoInt32 fd, GoInt64 offset, GoInt64 whence);
extern GoInt32 jfs_read(GoInt64 pid, GoInt32 fd, GoUintptr cbuf, GoInt32 count);
extern GoInt32 jfs_pread(GoInt64 pid, GoInt32 fd, GoUintptr cbuf, GoInt32 count, GoInt64 offset);
extern GoInt32 jfs_write(GoInt64 pid, GoInt32 fd, GoUintptr cbuf, GoInt32 count);
extern GoInt32 jfs_pwrite(GoInt64 pid, GoInt32 fd, GoUintptr cbuf, GoInt32 count, GoInt64 offset);
extern GoInt32 jfs_ftruncate(GoInt64 pid, GoInt32 fd, GoUint64 size);
extern GoInt32 jfs_flush(GoInt64 pid, GoInt32 fd);
extern GoInt32 jfs_fsync(GoInt64 pid, GoInt32 fd);
extern GoInt32 jfs_ranger_cfg(char* cname, GoUintptr buf, GoInt32 count);
extern GoInt32 jfs_close(GoInt64 pid, GoInt32 fd);
extern GoInt32 jfs_warmup(GoInt64 pid, GoInt64 h, char* _paths, GoInt32 numthreads, GoUint8 background, GoUint8 isEvict, GoUint8 isCheck, GoUint8** p_buf);
extern GoInt32 jfs_get_token(GoInt64 h, char* cname, GoUintptr buf, GoInt32 count, char* renewer);
extern GoInt64 jfs_renew_token(GoInt64 h, GoUint32 id, char* password);
extern GoInt32 jfs_cancel_token(GoInt64 h, GoUint32 id, char* password);

#ifdef __cplusplus
}
#endif
