#!/usr/bin/env python3
"""Dump ground truth for the lance-resolver golden fixture.

Parses the Lance binary layouts directly from the bytes of a fixture
generated by gen-fixtures.py -- the manifest footer plus protobuf wire
format, the V2 data file footer, the CMO table and each column's
ColumnMetadata -- and writes expected.json for the Go golden tests. This
extractor is deliberately independent of the Go resolver: layout knowledge
here comes from the upstream v11 sources pinned by gen-protos.sh, and all
offsets are read from the real fixture bytes.

Volatile values are normalized so that regenerating the fixture yields a
byte-stable JSON (CI diffs this file to detect upstream format drift):
  - data files: the writer assigns random names and permutes which content
    lands in which file across runs, so placeholders FILE0, FILE1, ... are
    assigned by CONTENT SIGNATURE (sorted layout), not by file name
  - transaction file -> TXN, manifest -> MANIFEST
  - creation timestamp / writer version: not exported (except the generator
    string, which is pinned and thus stable)

The Go golden test compares resolver output as multisets, which is stable
under the same file permutation; keep both sides in sync.

Usage: python dump_fixture.py <dataset-dir> <output-json>
"""

import json
import pathlib
import struct
import sys

MANIFEST_FOOTER_LEN = 16
FILE_FOOTER_LEN = 40
CMO_ENTRY_SIZE = 16
MAGIC = b"LANC"

# Protobuf field numbers, mirroring the .pb.go files generated by
# gen-protos.sh (authoritative for what the Go resolver decodes).
# Manifest: 1 fields, 2 fragments, 3 version, 12 transaction_file,
#           13 writer_version{1 library, 2 version}
# DataFragment: 1 id, 2 files
# DataFile: 1 path, 2 fields, 3 column_indices, 4 file_major_version
# Field: 1 type, 2 name, 3 id, 4 parent_id
# ColumnMetadata: 2 pages, 3 buffer_offsets, 4 buffer_sizes
# ColumnMetadata.Page: 1 buffer_offsets, 2 buffer_sizes


def read_varint(buf, i):
    value = shift = 0
    while True:
        b = buf[i]
        i += 1
        value |= (b & 0x7F) << shift
        if not b & 0x80:
            return value, i
        shift += 7


class Msg:
    """One protobuf message, decoded just far enough for this tool."""

    def __init__(self, buf):
        self.entries = {}  # field number -> [(wire_type, value)]
        i = 0
        n = len(buf)
        while i < n:
            tag, i = read_varint(buf, i)
            fn, wt = tag >> 3, tag & 7
            if wt == 0:
                v, i = read_varint(buf, i)
            elif wt == 2:
                ln, i = read_varint(buf, i)
                v = buf[i : i + ln]
                i += ln
            elif wt == 5:
                v, i = buf[i : i + 4], i + 4
            elif wt == 1:
                v, i = buf[i : i + 8], i + 8
            else:
                raise ValueError(f"unsupported wire type {wt}")
            self.entries.setdefault(fn, []).append((wt, v))

    def varints(self, fn):
        """Repeated varint field, packed or unpacked."""
        out = []
        for wt, v in self.entries.get(fn, []):
            if wt == 0:
                out.append(v)
            elif wt == 2:
                i = 0
                while i < len(v):
                    x, i = read_varint(v, i)
                    out.append(x)
        return out

    def one_varint(self, fn, default=0):
        for wt, v in self.entries.get(fn, []):
            if wt == 0:
                return v
        return default

    def one_bytes(self, fn):
        for wt, v in self.entries.get(fn, []):
            if wt == 2:
                return v
        return None

    def one_string(self, fn, default=""):
        raw = self.one_bytes(fn)
        return default if raw is None else raw.decode()

    def messages(self, fn):
        return [Msg(v) for wt, v in self.entries.get(fn, []) if wt == 2]


def to_i64(v):
    return v - (1 << 64) if v >= (1 << 63) else v


def parse_manifest(path):
    data = path.read_bytes()
    if len(data) < MANIFEST_FOOTER_LEN:
        raise ValueError(f"manifest too short: {len(data)} bytes")
    footer = data[-MANIFEST_FOOTER_LEN:]
    if footer[12:16] != MAGIC:
        raise ValueError(f"bad manifest magic {footer[12:16]!r} in {path}")
    manifest_pos, major, minor = struct.unpack("<qhh", footer[0:12])
    msg_len = struct.unpack("<I", data[manifest_pos : manifest_pos + 4])[0]
    msg = Msg(data[manifest_pos + 4 : manifest_pos + 4 + msg_len])

    fields = []
    for fm in msg.messages(1):
        fields.append(
            {
                "name": fm.one_string(2),
                "id": to_i64(fm.one_varint(3)),
                "parent_id": to_i64(fm.one_varint(4)),
            }
        )
    fragments = []
    for fr in msg.messages(2):
        files = []
        for df in fr.messages(2):
            files.append(
                {
                    "path": df.one_string(1),
                    "field_ids": [to_i64(v) for v in df.varints(2)],
                    "column_indices": [to_i64(v) for v in df.varints(3)],
                    "file_major_version": df.one_varint(4),
                }
            )
        fragments.append({"id": fr.one_varint(1), "files": files})

    writer = msg.messages(13)
    generator = (
        f"{writer[0].one_string(1)}-{writer[0].one_string(2)}" if writer else "unknown"
    )
    return {
        "version": msg.one_varint(3),
        "manifest_pos": manifest_pos,
        "footer_version": [major, minor],
        "transaction_file": msg.one_string(12),
        "generator": generator,
        "fields": fields,
        "fragments": fragments,
    }


def parse_data_file(path):
    data = path.read_bytes()
    if len(data) < FILE_FOOTER_LEN:
        raise ValueError(f"data file too short: {len(data)} bytes")
    footer = data[-FILE_FOOTER_LEN:]
    if footer[36:40] != MAGIC:
        raise ValueError(f"bad file magic {footer[36:40]!r} in {path}")
    col_meta_start, cmo_start, gbo_start = struct.unpack("<QQQ", footer[0:24])
    num_global_buffers, num_columns = struct.unpack("<II", footer[24:32])
    major, minor = struct.unpack("<HH", footer[32:36])

    columns = []
    for idx in range(num_columns):
        off = cmo_start + CMO_ENTRY_SIZE * idx
        pos, ln = struct.unpack("<QQ", data[off : off + CMO_ENTRY_SIZE])
        cm = Msg(data[pos : pos + ln])
        pages = [(pm.varints(1), pm.varints(2)) for pm in cm.messages(2)]
        columns.append(
            {
                "cm_pos": pos,
                "cm_len": ln,
                "buffer_offsets": cm.varints(3),
                "buffer_sizes": cm.varints(4),
                "pages": pages,
            }
        )
    return {
        "footer": {
            "column_metadata_start": col_meta_start,
            "cmo_table_start": cmo_start,
            "gbo_table_start": gbo_start,
            "num_global_buffers": num_global_buffers,
            "num_columns": num_columns,
            "footer_version": [major, minor],
        },
        "columns": columns,
    }


def merge_ranges(ranges):
    merged = []
    for start, end in sorted(ranges):
        if merged and start <= merged[-1][1]:
            if end > merged[-1][1]:
                merged[-1][1] = end
        else:
            merged.append([start, end])
    return merged


def column_ranges(col, include_pages):
    ranges = [[col["cm_pos"], col["cm_pos"] + col["cm_len"]]]

    def add(offsets, sizes):
        for o, s in zip(offsets, sizes):
            if s and o + s >= o:  # skip empty and overflowing (corrupt) entries
                ranges.append([o, o + s])

    if include_pages:
        for offs, sizes in col["pages"]:
            add(offs, sizes)
    add(col["buffer_offsets"], col["buffer_sizes"])
    return merge_ranges(ranges)


def leaf_parent_ids(fields):
    ids = {f["id"] for f in fields}
    parents = set()
    for f in fields:
        pid = f["parent_id"]
        if pid != f["id"] and pid in ids:
            parents.add(pid)
    return parents


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    ds = pathlib.Path(sys.argv[1])
    out_path = pathlib.Path(sys.argv[2])

    versions_dir = ds / "_versions"
    manifest_name = sorted(
        p.name for p in versions_dir.glob("*.manifest")
    )[-1]
    manifest = parse_manifest(versions_dir / manifest_name)

    data_files = sorted(p.name for p in (ds / "data").glob("*.lance"))

    parents = leaf_parent_ids(manifest["fields"])
    id_to_name = {f["id"]: f["name"] for f in manifest["fields"]}

    files = []
    for name in data_files:
        parsed = parse_data_file(ds / "data" / name)
        # Map column index -> schema field via this file's DataFile entry.
        col_to_field = {}
        file_major = None
        for frag in manifest["fragments"]:
            for df in frag["files"]:
                if df["path"] == name:
                    file_major = df["file_major_version"]
                    for fid, cidx in zip(df["field_ids"], df["column_indices"]):
                        col_to_field[cidx] = fid

        columns = []
        for idx, col in enumerate(parsed["columns"]):
            fid = col_to_field.get(idx)
            columns.append(
                {
                    "name": id_to_name.get(fid),
                    "leaf": fid is not None and fid not in parents,
                    "cm_pos": col["cm_pos"],
                    "cm_len": col["cm_len"],
                    "ranges_meta": column_ranges(col, False),
                    "ranges_pages": column_ranges(col, True),
                }
            )
        files.append(
            {
                "file_major_version": file_major,
                "footer": parsed["footer"],
                "columns": columns,
            }
        )

    # Random file names plus writer-side content permutation: assign
    # placeholders by content signature so expected.json is regen-stable.
    files.sort(key=lambda f: json.dumps(f, sort_keys=True))
    for i, f in enumerate(files):
        f["placeholder"] = f"FILE{i}"

    full_resolve = ["MANIFEST"] + [f["placeholder"] for f in files]
    if manifest["transaction_file"]:
        full_resolve.append("TXN")

    expected = {
        "format": "lance-fixture-expected/1",
        "generator": manifest["generator"],
        "manifest": {
            "version": manifest["version"],
            "manifest_pos": manifest["manifest_pos"],
            "footer_version": manifest["footer_version"],
            "transaction_file": "TXN" if manifest["transaction_file"] else None,
        },
        "files": files,
        "full_resolve": sorted(full_resolve),
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(expected, indent=2, sort_keys=True) + "\n")
    print(f"expected ground truth written to {out_path}")
    print(f"  generator: {expected['generator']}")
    print(f"  data files: {len(files)}, columns in FILE0: {len(files[0]['columns'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
