{
 "title": "JuiceFS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "name", "query": "test" }
  ]
 },
 "panels": [
  {
   "title": "Data Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(juicefs_used_space{vol_name=\"$name\"})",
     "legendFormat": "Data Size"
    }
   ]
  },
  {
   "title": "Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(juicefs_used_inodes{vol_name=\"$name\"})",
     "legendFormat": "Files"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(juicefs_uptime{vol_name=\"$name\"})",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_ops_durations_histogram_seconds_count{vol_name=\"$name\"}[1m]) < 5000000000) by (node)",
     "legendFormat": "Write {{node}}"
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_written_size_bytes_sum{vol_name=\"$name\"}[1m]) < 5000000000) by (node)",
     "legendFormat": "Write {{node}}"
    },
    {
     "expr": "sum(rate(juicefs_fuse_read_size_bytes_sum{vol_name=\"$name\"}[1m]) < 5000000000) by (node)",
     "legendFormat": "Read {{node}}"
    }
   ]
  },
  {
   "title": "IO Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_ops_durations_histogram_seconds_sum{vol_name=\"$name\"}[1m])) by  (node,mp) * 1000000 / sum(rate(juicefs_fuse_ops_durations_histogram_seconds_count{vol_name=\"$name\"}[1m])) by  (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Redis Transcations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_redis_tx_durations_histogram_seconds_count{vol_name=\"$name\"}[1m])) by  (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Redis Transcation Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_redis_tx_durations_histogram_seconds_sum{vol_name=\"$name\"}[1m])) by  (node,mp) * 1000000 / sum(rate(juicefs_redis_tx_durations_histogram_seconds_count{vol_name=\"$name\"}[1m])) by  (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Redis Transaction Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_redis_transaction_restart{vol_name=~\"$name\"}[1m])) by (node)",
     "legendFormat": "Restarts {{node}}"
    }
   ]
  },
  {
   "title": "Objects Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_durations_histogram_seconds_count{vol_name=\"$name\"}[1m])) by  (method)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(juicefs_object_request_errors{vol_name=\"$name\"}[1m])) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Objects Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_data_bytes{method=\"PUT\",vol_name=\"$name\"}[1m])) by  (node,method)",
     "legendFormat": "{{method}} {{node}}"
    },
    {
     "expr": "sum(rate(juicefs_object_request_data_bytes{method=\"GET\",vol_name=\"$name\"}[1m])) by  (node,method)",
     "legendFormat": "{{method}} {{node}}"
    }
   ]
  },
  {
   "title": "Objects Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_durations_histogram_seconds_sum{vol_name=\"$name\"}[1m])) by  (node) * 1000000 / sum(rate(juicefs_object_request_durations_histogram_seconds_count{vol_name=\"$name\"}[1m])) by  (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Client CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_cpu_usage{vol_name=\"$name\"}[1m])*100 < 1000) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(juicefs_memory{vol_name=\"$name\"}) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(juicefs_blockcache_bytes{vol_name=\"$name\"}) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(juicefs_blockcache_blocks{vol_name=\"$name\"}) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Hitrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_blockcache_hits{vol_name=\"$name\"}[1m])) by (node,mp) / (sum(rate(juicefs_blockcache_hits{vol_name=\"$name\"}[1m])) by (node,mp) + sum(rate(juicefs_blockcache_miss{vol_name=\"$name\"}[1m])) by (node,mp))",
     "legendFormat": "Hits {{node}}:{{mp}}"
    },
    {
     "expr": "sum(rate(juicefs_blockcache_hit_bytes{vol_name=\"$name\"}[1m])) by (node,mp) / (sum(rate(juicefs_blockcache_hit_bytes{vol_name=\"$name\"}[1m])) by (node,mp) + sum(rate(juicefs_blockcache_miss_bytes{vol_name=\"$name\"}[1m])) by (node,mp))",
     "legendFormat": "HitBytes {{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_compact_size_histogram_bytes_count{vol_name=\"$name\"}[1m])) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Compacted Data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(juicefs_compact_size_histogram_bytes_sum{vol_name=\"$name\"}[1m])) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Open File Handlers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(juicefs_fuse_open_handlers{vol_name=\"$name\"}) by (node,mp)",
     "legendFormat": "{{node}}:{{mp}}"
    }
   ]
  }
 ]
}