name: 'Version Compatible Hypo'
description: 'Version Compatible Hypo action'
inputs:
  old_juicefs_version:
    description: 'old juicefs'
    required: true
    default: ''
  meta_url:  
    description: 'meta url'
    required: true
    default: 'redis://localhost/1'
  storage:
    description: 'storage'
    required: true
    default: "minio"

runs:
  using: "composite"
  steps:  
    - name: Download old version
      shell: bash
      run: | 
        filename=juicefs-${{inputs.old_juicefs_version}}-linux-amd64.tar.gz
        echo filename is: $filename
        url=$(curl -s https://api.github.com/repos/juicedata/juicefs/releases | grep browser_download_url | grep $filename | awk -F\" '{print $4}' | head -1)
        echo download url is: $url
        wget -q $url
        tar -zxf $filename
        mv juicefs juicefs-${{inputs.old_juicefs_version}}
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.x'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Make Juicefs
      shell: bash
      run: | 
        make juicefs
        

    - name: Setup minio
      shell: bash
      run: |
        docker run -d -p 9000:9000 --name minio \
                    -e "MINIO_ACCESS_KEY=minioadmin" \
                    -e "MINIO_SECRET_KEY=minioadmin" \
                    -v /tmp/data:/data \
                    -v /tmp/config:/root/.minio \
                    minio/minio server /data
        
    - name: Install tools
      shell: bash
      run: | 
        wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin
        sudo apt install redis-tools
        sudo pip install hypothesis
        sudo pip install minio
        
    - name: Test
      shell: bash
      run: |
        export META_URL=${{inputs.meta_url}}
        export STORAGE=${{inputs.storage}}
        version=`./juicefs version | awk -F" " '{print $3}' | awk -F+ '{print $1}'`
        mv juicefs juicefs-$version
        export NEW_JFS_BIN="juicefs-$version"
        export OLD_JFS_BIN="juicefs-${{inputs.old_juicefs_version}}"

        # python3 .github/scripts/test_action_log.py
        python3 .github/scripts/testVersionCompatible.py
        
    - name: Display log
      if: ${{ always() }}
      shell: bash
      run: | 
        if [ -f "~/.juicefs/juicefs.log" ]; then
          tail -500 ~/.juicefs/juicefs.log
          grep "<FATAL>:" ~/.juicefs/juicefs.log && exit 1 || true
        fi