// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: file.proto

package lance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported encodings.
type Encoding int32

const (
	// Invalid encoding.
	Encoding_NONE Encoding = 0
	// Plain encoding.
	Encoding_PLAIN Encoding = 1
	// Var-length binary encoding.
	Encoding_VAR_BINARY Encoding = 2
	// Dictionary encoding.
	Encoding_DICTIONARY Encoding = 3
	// Run-length encoding.
	Encoding_RLE Encoding = 4
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "NONE",
		1: "PLAIN",
		2: "VAR_BINARY",
		3: "DICTIONARY",
		4: "RLE",
	}
	Encoding_value = map[string]int32{
		"NONE":       0,
		"PLAIN":      1,
		"VAR_BINARY": 2,
		"DICTIONARY": 3,
		"RLE":        4,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

type Field_Type int32

const (
	Field_PARENT   Field_Type = 0
	Field_REPEATED Field_Type = 1
	Field_LEAF     Field_Type = 2
)

// Enum value maps for Field_Type.
var (
	Field_Type_name = map[int32]string{
		0: "PARENT",
		1: "REPEATED",
		2: "LEAF",
	}
	Field_Type_value = map[string]int32{
		"PARENT":   0,
		"REPEATED": 1,
		"LEAF":     2,
	}
)

func (x Field_Type) Enum() *Field_Type {
	p := new(Field_Type)
	*p = x
	return p
}

func (x Field_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[1].Descriptor()
}

func (Field_Type) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[1]
}

func (x Field_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_Type.Descriptor instead.
func (Field_Type) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4, 0}
}

// A file descriptor that describes the contents of a Lance file
type FileDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema of the file
	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// The number of rows in the file
	Length        uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDescriptor) Reset() {
	*x = FileDescriptor{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDescriptor) ProtoMessage() {}

func (x *FileDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDescriptor.ProtoReflect.Descriptor instead.
func (*FileDescriptor) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileDescriptor) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *FileDescriptor) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// A schema which describes the data type of each of the columns
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All fields in this file, including the nested fields.
	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Schema metadata.
	Metadata      map[string][]byte `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata of one Lance file.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position of the manifest in the file. If it is zero, the manifest is stored
	// externally.
	ManifestPosition uint64 `protobuf:"varint,1,opt,name=manifest_position,json=manifestPosition,proto3" json:"manifest_position,omitempty"`
	// Logical offsets of each chunk group, i.e., number of the rows in each
	// chunk.
	BatchOffsets []int32 `protobuf:"varint,2,rep,packed,name=batch_offsets,json=batchOffsets,proto3" json:"batch_offsets,omitempty"`
	// The file position that page table is stored.
	//
	// A page table is a matrix of N x M x 2, where N = num_fields, and M =
	// num_batches. Each cell in the table is a pair of <position:int64,
	// length:int64> of the page. Both position and length are int64 values. The
	// <position, length> of all the pages in the same column are then
	// contiguously stored.
	//
	// Every field that is a part of the file will have a run in the page table.
	// This includes struct columns, which will have a run of length 0 since
	// they don't store any actual data.
	//
	// For example, for the column 5 and batch 4, we have:
	// ```text
	//
	//	position = page_table[5][4][0];
	//	length = page_table[5][4][1];
	//
	// ```
	PageTablePosition uint64                       `protobuf:"varint,3,opt,name=page_table_position,json=pageTablePosition,proto3" json:"page_table_position,omitempty"`
	Statistics        *Metadata_StatisticsMetadata `protobuf:"bytes,5,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetManifestPosition() uint64 {
	if x != nil {
		return x.ManifestPosition
	}
	return 0
}

func (x *Metadata) GetBatchOffsets() []int32 {
	if x != nil {
		return x.BatchOffsets
	}
	return nil
}

func (x *Metadata) GetPageTablePosition() uint64 {
	if x != nil {
		return x.PageTablePosition
	}
	return 0
}

func (x *Metadata) GetStatistics() *Metadata_StatisticsMetadata {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// Dictionary field metadata
type Dictionary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The file offset for storing the dictionary value.
	// / It is only valid if encoding is DICTIONARY.
	// /
	// / The logic type presents the value type of the column, i.e., string value.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// / The length of dictionary values.
	Length        int64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *Dictionary) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Dictionary) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Field metadata for a column.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Field_Type             `protobuf:"varint,1,opt,name=type,proto3,enum=lance.file.Field_Type" json:"type,omitempty"`
	// Fully qualified name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// / Field Id.
	// /
	// / See the comment in `DataFile.fields` for how field ids are assigned.
	Id int32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// / Parent Field ID. If not set, this is a top-level column.
	ParentId int32 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Logical types, support parameterized Arrow Type.
	//
	// PARENT types will always have logical type "struct".
	//
	// REPEATED types may have logical types:
	// * "list"
	// * "large_list"
	// * "list.struct"
	// * "large_list.struct"
	// The final two are used if the list values are structs, and therefore the
	// field is both implicitly REPEATED and PARENT.
	//
	// LEAF types may have logical types:
	// * "null"
	// * "bool"
	// * "int8" / "uint8"
	// * "int16" / "uint16"
	// * "int32" / "uint32"
	// * "int64" / "uint64"
	// * "halffloat" / "float" / "double"
	// * "string" / "large_string"
	// * "binary" / "large_binary"
	// * "date32:day"
	// * "date64:ms"
	// * "decimal:128:{precision}:{scale}" / "decimal:256:{precision}:{scale}"
	// * "time:{unit}" / "timestamp:{unit}" / "duration:{unit}", where unit is
	// "s", "ms", "us", "ns"
	// * "dict:{value_type}:{index_type}:false"
	LogicalType string `protobuf:"bytes,5,opt,name=logical_type,json=logicalType,proto3" json:"logical_type,omitempty"`
	// If this field is nullable.
	Nullable bool `protobuf:"varint,6,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// optional field metadata (e.g. extension type name/parameters)
	Metadata             map[string][]byte `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnenforcedPrimaryKey bool              `protobuf:"varint,12,opt,name=unenforced_primary_key,json=unenforcedPrimaryKey,proto3" json:"unenforced_primary_key,omitempty"`
	// Position of this field in the primary key (1-based).
	// 0 means the field is part of the primary key but uses schema field id for ordering.
	// When set to a positive value, primary key fields are ordered by this position.
	UnenforcedPrimaryKeyPosition uint32 `protobuf:"varint,13,opt,name=unenforced_primary_key_position,json=unenforcedPrimaryKeyPosition,proto3" json:"unenforced_primary_key_position,omitempty"`
	// Reserved for future use. Use unenforced_clustering_key_position instead.
	UnenforcedClusteringKey bool `protobuf:"varint,14,opt,name=unenforced_clustering_key,json=unenforcedClusteringKey,proto3" json:"unenforced_clustering_key,omitempty"`
	// Position of this field in the clustering key (1-based).
	// 0 means the field is not part of the clustering key.
	UnenforcedClusteringKeyPosition uint32 `protobuf:"varint,15,opt,name=unenforced_clustering_key_position,json=unenforcedClusteringKeyPosition,proto3" json:"unenforced_clustering_key_position,omitempty"`
	// Deprecated: Only used in V1 file format. V2 uses variable encodings defined
	// per page.
	//
	// The global encoding to use for this field.
	Encoding Encoding `protobuf:"varint,7,opt,name=encoding,proto3,enum=lance.file.Encoding" json:"encoding,omitempty"`
	// Deprecated: Only used in V1 file format. V2 dynamically chooses when to
	// do dictionary encoding and keeps the dictionary in the data files.
	//
	// The file offset for storing the dictionary value.
	// It is only valid if encoding is DICTIONARY.
	//
	// The logic type presents the value type of the column, i.e., string value.
	Dictionary *Dictionary `protobuf:"bytes,8,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	// Deprecated: optional extension type name, use metadata field
	// ARROW:extension:name
	ExtensionName string `protobuf:"bytes,9,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetType() Field_Type {
	if x != nil {
		return x.Type
	}
	return Field_PARENT
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Field) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Field) GetLogicalType() string {
	if x != nil {
		return x.LogicalType
	}
	return ""
}

func (x *Field) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Field) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Field) GetUnenforcedPrimaryKey() bool {
	if x != nil {
		return x.UnenforcedPrimaryKey
	}
	return false
}

func (x *Field) GetUnenforcedPrimaryKeyPosition() uint32 {
	if x != nil {
		return x.UnenforcedPrimaryKeyPosition
	}
	return 0
}

func (x *Field) GetUnenforcedClusteringKey() bool {
	if x != nil {
		return x.UnenforcedClusteringKey
	}
	return false
}

func (x *Field) GetUnenforcedClusteringKeyPosition() uint32 {
	if x != nil {
		return x.UnenforcedClusteringKeyPosition
	}
	return 0
}

func (x *Field) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_NONE
}

func (x *Field) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

func (x *Field) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

type Metadata_StatisticsMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema of the statistics.
	//
	// This might be empty, meaning there are no statistics. It also might not
	// contain statistics for every field.
	Schema []*Field `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	// The field ids of the statistics leaf fields.
	//
	// This plays a similar role to the `fields` field in the DataFile message.
	// Each of these field ids corresponds to a field in the stats_schema. There
	// is one per column in the stats page table.
	Fields []int32 `protobuf:"varint,2,rep,packed,name=fields,proto3" json:"fields,omitempty"`
	// The file position of the statistics page table
	//
	// The page table is a matrix of N x 2, where N = length of stats_fields.
	// This is the same layout as the main page table, except there is always
	// only one batch.
	//
	// For example, to get the stats column 5, we have:
	// ```text
	//
	//	position = stats_page_table[5][0];
	//	length = stats_page_table[5][1];
	//
	// ```
	PageTablePosition uint64 `protobuf:"varint,3,opt,name=page_table_position,json=pageTablePosition,proto3" json:"page_table_position,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata_StatisticsMetadata) Reset() {
	*x = Metadata_StatisticsMetadata{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_StatisticsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_StatisticsMetadata) ProtoMessage() {}

func (x *Metadata_StatisticsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_StatisticsMetadata.ProtoReflect.Descriptor instead.
func (*Metadata_StatisticsMetadata) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Metadata_StatisticsMetadata) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Metadata_StatisticsMetadata) GetFields() []int32 {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Metadata_StatisticsMetadata) GetPageTablePosition() uint64 {
	if x != nil {
		return x.PageTablePosition
	}
	return 0
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\n" +
	"lance.file\"T\n" +
	"\x0eFileDescriptor\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.lance.file.SchemaR\x06schema\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\"\xae\x01\n" +
	"\x06Schema\x12)\n" +
	"\x06fields\x18\x01 \x03(\v2\x11.lance.file.FieldR\x06fields\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .lance.file.Schema.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe5\x02\n" +
	"\bMetadata\x12+\n" +
	"\x11manifest_position\x18\x01 \x01(\x04R\x10manifestPosition\x12#\n" +
	"\rbatch_offsets\x18\x02 \x03(\x05R\fbatchOffsets\x12.\n" +
	"\x13page_table_position\x18\x03 \x01(\x04R\x11pageTablePosition\x12G\n" +
	"\n" +
	"statistics\x18\x05 \x01(\v2'.lance.file.Metadata.StatisticsMetadataR\n" +
	"statistics\x1a\x87\x01\n" +
	"\x12StatisticsMetadata\x12)\n" +
	"\x06schema\x18\x01 \x03(\v2\x11.lance.file.FieldR\x06schema\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\x05R\x06fields\x12.\n" +
	"\x13page_table_position\x18\x03 \x01(\x04R\x11pageTablePositionJ\x04\b\x04\x10\x05\"<\n" +
	"\n" +
	"Dictionary\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"\x85\x06\n" +
	"\x05Field\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.lance.file.Field.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x05R\bparentId\x12!\n" +
	"\flogical_type\x18\x05 \x01(\tR\vlogicalType\x12\x1a\n" +
	"\bnullable\x18\x06 \x01(\bR\bnullable\x12;\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1f.lance.file.Field.MetadataEntryR\bmetadata\x124\n" +
	"\x16unenforced_primary_key\x18\f \x01(\bR\x14unenforcedPrimaryKey\x12E\n" +
	"\x1funenforced_primary_key_position\x18\r \x01(\rR\x1cunenforcedPrimaryKeyPosition\x12:\n" +
	"\x19unenforced_clustering_key\x18\x0e \x01(\bR\x17unenforcedClusteringKey\x12K\n" +
	"\"unenforced_clustering_key_position\x18\x0f \x01(\rR\x1funenforcedClusteringKeyPosition\x120\n" +
	"\bencoding\x18\a \x01(\x0e2\x14.lance.file.EncodingR\bencoding\x126\n" +
	"\n" +
	"dictionary\x18\b \x01(\v2\x16.lance.file.DictionaryR\n" +
	"dictionary\x12%\n" +
	"\x0eextension_name\x18\t \x01(\tR\rextensionName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"*\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06PARENT\x10\x00\x12\f\n" +
	"\bREPEATED\x10\x01\x12\b\n" +
	"\x04LEAF\x10\x02J\x04\b\v\x10\fR\rstorage_class*H\n" +
	"\bEncoding\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05PLAIN\x10\x01\x12\x0e\n" +
	"\n" +
	"VAR_BINARY\x10\x02\x12\x0e\n" +
	"\n" +
	"DICTIONARY\x10\x03\x12\a\n" +
	"\x03RLE\x10\x04b\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_file_proto_goTypes = []any{
	(Encoding)(0),                       // 0: lance.file.Encoding
	(Field_Type)(0),                     // 1: lance.file.Field.Type
	(*FileDescriptor)(nil),              // 2: lance.file.FileDescriptor
	(*Schema)(nil),                      // 3: lance.file.Schema
	(*Metadata)(nil),                    // 4: lance.file.Metadata
	(*Dictionary)(nil),                  // 5: lance.file.Dictionary
	(*Field)(nil),                       // 6: lance.file.Field
	nil,                                 // 7: lance.file.Schema.MetadataEntry
	(*Metadata_StatisticsMetadata)(nil), // 8: lance.file.Metadata.StatisticsMetadata
	nil,                                 // 9: lance.file.Field.MetadataEntry
}
var file_file_proto_depIdxs = []int32{
	3, // 0: lance.file.FileDescriptor.schema:type_name -> lance.file.Schema
	6, // 1: lance.file.Schema.fields:type_name -> lance.file.Field
	7, // 2: lance.file.Schema.metadata:type_name -> lance.file.Schema.MetadataEntry
	8, // 3: lance.file.Metadata.statistics:type_name -> lance.file.Metadata.StatisticsMetadata
	1, // 4: lance.file.Field.type:type_name -> lance.file.Field.Type
	9, // 5: lance.file.Field.metadata:type_name -> lance.file.Field.MetadataEntry
	0, // 6: lance.file.Field.encoding:type_name -> lance.file.Encoding
	5, // 7: lance.file.Field.dictionary:type_name -> lance.file.Dictionary
	6, // 8: lance.file.Metadata.StatisticsMetadata.schema:type_name -> lance.file.Field
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		EnumInfos:         file_file_proto_enumTypes,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
