/*
 * JuiceFS, Copyright 2026 Juicedata, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package meta

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Changelog operations generated by genLog.
const (
	OpCreate               = "CREATE"
	OpUnlink               = "UNLINK"
	OpUnlinkBatch          = "UNLINKBATCH"
	OpRmdir                = "RMDIR"
	OpMove                 = "MOVE"
	OpLink                 = "LINK"
	OpSetAttr              = "SETATTR"
	OpTruncate             = "TRUNCATE"
	OpFallocate            = "FALLOCATE"
	OpAccess               = "ACCESS"
	OpWrite                = "WRITE"
	OpCopyFileRange        = "COPYFILERANGE"
	OpDelChunk             = "DELCHUNK"
	OpCompactChunk         = "COMPACTCHUNK"
	OpDeleteSlice          = "DELETESLICE"
	OpCleanupDelayedSlices = "CLEANUP_DELAYED_SLICES"
	OpCleanupTrashSlices   = "CLEANUP_TRASH_SLICES"
	OpSetXattr             = "SETXATTR"
	OpRemoveXattr          = "REMOVEXATTR"
	OpSetFacl              = "SETFACL"
	OpLoadDumpedAcls       = "LOADDUMPEDACLS"
	OpSetQuota             = "SETQUOTA"
	OpDelQuota             = "DELQUOTA"
	OpDirStat              = "DIRSTAT"
	OpRepairDir            = "REPAIRDIR"
	OpClone                = "CLONE"
	OpAttach               = "ATTACH"
	OpCleanup              = "CLEANUP"
	OpNewSession           = "NEWSESSION"
	OpCleanSession         = "CLEANSESSION"
	OpDelSustained         = "DELSUSTAINED"
	OpSet                  = "SET"
	OpIncrCounter          = "INCR_COUNTER"
	OpInitDirStats         = "INIT_ENABLE_DIRSTATS"
	OpInitUserGroupQuota   = "INIT_ENABLE_USERGROUPQUOTA"
	OpStoreToken           = "STORETOKEN"
	OpUpdateToken          = "UPDATETOKEN"
	OpDeleteTokens         = "DELETETOKENS"
)

// variadic marks a variable argument or result count.
const variadic = -1

type changelogOpSpec struct {
	args    int
	results int
}

var changelogOps = map[string]changelogOpSpec{
	OpCreate:               {10, 1},
	OpUnlink:               {5, 1},
	OpUnlinkBatch:          {variadic, variadic},
	OpRmdir:                {3, 1},
	OpMove:                 {7, 1},
	OpLink:                 {4, 1},
	OpSetAttr:              {14, 0},
	OpTruncate:             {4, 0},
	OpFallocate:            {4, 0},
	OpAccess:               {1, 0},
	OpWrite:                {7, 1},
	OpCopyFileRange:        {5, 1},
	OpDelChunk:             {2, 0},
	OpCompactChunk:         {7, 0},
	OpDeleteSlice:          {2, 0},
	OpCleanupDelayedSlices: {2, 0},
	OpCleanupTrashSlices:   {2, 0},
	OpSetXattr:             {4, 0},
	OpRemoveXattr:          {2, 0},
	OpSetFacl:              {3, 0},
	OpLoadDumpedAcls:       {1, 0},
	OpSetQuota:             {4, 0},
	OpDelQuota:             {2, 0},
	OpDirStat:              {4, 0},
	OpRepairDir:            {1, 0},
	OpClone:                {7, 1},
	OpAttach:               {3, 0},
	OpCleanup:              {1, 0},
	OpNewSession:           {3, 0},
	OpCleanSession:         {1, 0},
	OpDelSustained:         {2, 0},
	OpSet:                  {2, 0},
	OpIncrCounter:          {2, 0},
	OpInitDirStats:         {0, 0},
	OpInitUserGroupQuota:   {0, 0},
	OpStoreToken:           {2, 0},
	OpUpdateToken:          {2, 0},
	OpDeleteTokens:         {variadic, 0},
}

// ErrUnknownChangelogOp indicates an operation unknown to Validate.
var ErrUnknownChangelogOp = errors.New("unknown changelog operation")

// ErrChangelogStop stops ScanChangelog without reporting a failure.
var ErrChangelogStop = errors.New("stop scanning changelog")

type ChangelogScanOption struct {
	// From is the resume version; 0 starts from the latest version.
	From int64
	// Follow waits for new entries after catching up.
	Follow bool
}

// ChangeEntry holds a parsed entry with decoded Args and Result.
type ChangeEntry struct {
	Ver    int64
	Time   time.Time
	Op     string
	Args   []string
	Result []string
	Sid    uint64
	TxnId  uint64
}

// ParseChangeEntry parses one line produced by genLog:
//
//	<SEC>.<NSEC>|<OP>(<ARG>,...)[:<RESULT>]|(<SID>,<TXNID>)
//
// Encoded arguments escape ',', '(' and ')', leaving separators unambiguous.
func ParseChangeEntry(ver int64, entry string) (*ChangeEntry, error) {
	ts, err := parseChangelogTime(entry)
	if err != nil {
		return nil, err
	}
	head := strings.IndexByte(entry, '|')

	// '(' is escaped inside encoded arguments, so "|(" can only be the tail.
	tail := strings.LastIndex(entry, "|(")
	if tail <= head || entry[len(entry)-1] != ')' {
		return nil, fmt.Errorf("no (sid,txnid) suffix: %q", entry)
	}
	sid, txnId, err := parseSidTxn(entry[tail+2 : len(entry)-1])
	if err != nil {
		return nil, fmt.Errorf("parse (sid,txnid) of %q: %w", entry, err)
	}

	body := entry[head+1 : tail]
	open := strings.IndexByte(body, '(')
	if open < 0 {
		return nil, fmt.Errorf("no operation arguments: %q", entry)
	}
	op := body[:open]
	if !isChangelogOpName(op) {
		return nil, fmt.Errorf("invalid operation name %q in %q", op, entry)
	}
	rel := strings.IndexByte(body[open+1:], ')')
	if rel < 0 {
		return nil, fmt.Errorf("unclosed operation arguments: %q", entry)
	}
	closing := open + 1 + rel

	args, err := splitAndDecode(body[open+1 : closing])
	if err != nil {
		return nil, fmt.Errorf("decode arguments of %q: %w", entry, err)
	}
	var result []string
	if rest := body[closing+1:]; rest != "" {
		if rest[0] != ':' {
			return nil, fmt.Errorf("unexpected trailer %q in %q", rest, entry)
		}
		if result, err = splitAndDecode(rest[1:]); err != nil {
			return nil, fmt.Errorf("decode result of %q: %w", entry, err)
		}
	}
	return &ChangeEntry{
		Ver:    ver,
		Time:   ts,
		Op:     op,
		Args:   args,
		Result: result,
		Sid:    sid,
		TxnId:  txnId,
	}, nil
}

// Validate checks the operation and its argument and result counts.
func (e *ChangeEntry) Validate() error {
	spec, ok := changelogOps[e.Op]
	if !ok {
		return fmt.Errorf("%w: %s", ErrUnknownChangelogOp, e.Op)
	}
	if e.Op == OpUnlinkBatch {
		// parent, name..., trash, updateParent : inode...
		if len(e.Args) < 4 {
			return fmt.Errorf("%s: expect at least 4 arguments, got %d", e.Op, len(e.Args))
		}
		if names := len(e.Args) - 3; names != len(e.Result) {
			return fmt.Errorf("%s: %d names but %d inodes", e.Op, names, len(e.Result))
		}
		return nil
	}
	if spec.args == variadic {
		if len(e.Args) == 0 {
			return fmt.Errorf("%s: expect at least 1 argument", e.Op)
		}
	} else if len(e.Args) != spec.args {
		return fmt.Errorf("%s: expect %d arguments, got %d", e.Op, spec.args, len(e.Args))
	}
	if spec.results != variadic && len(e.Result) != spec.results {
		return fmt.Errorf("%s: expect %d results, got %d", e.Op, spec.results, len(e.Result))
	}
	return nil
}

// BatchNames returns the entry names of an UNLINKBATCH operation.
func (e *ChangeEntry) BatchNames() []string { return e.Args[1 : len(e.Args)-2] }

func (e *ChangeEntry) Str(i int) (string, error) {
	if i < 0 || i >= len(e.Args) {
		return "", fmt.Errorf("%s: argument %d out of range (%d)", e.Op, i, len(e.Args))
	}
	return e.Args[i], nil
}

func (e *ChangeEntry) Uint64(i int) (uint64, error) {
	s, err := e.Str(i)
	if err != nil {
		return 0, err
	}
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%s: argument %d %q is not an unsigned integer", e.Op, i, s)
	}
	return v, nil
}

func (e *ChangeEntry) Int64(i int) (int64, error) {
	s, err := e.Str(i)
	if err != nil {
		return 0, err
	}
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%s: argument %d %q is not an integer", e.Op, i, s)
	}
	return v, nil
}

func (e *ChangeEntry) Uint32(i int) (uint32, error) {
	v, err := e.Uint64(i)
	if err != nil {
		return 0, err
	}
	if v > 0xFFFFFFFF {
		return 0, fmt.Errorf("%s: argument %d %d overflows uint32", e.Op, i, v)
	}
	return uint32(v), nil
}

func (e *ChangeEntry) Uint16(i int) (uint16, error) {
	v, err := e.Uint64(i)
	if err != nil {
		return 0, err
	}
	if v > 0xFFFF {
		return 0, fmt.Errorf("%s: argument %d %d overflows uint16", e.Op, i, v)
	}
	return uint16(v), nil
}

func (e *ChangeEntry) Uint8(i int) (uint8, error) {
	v, err := e.Uint64(i)
	if err != nil {
		return 0, err
	}
	if v > 0xFF {
		return 0, fmt.Errorf("%s: argument %d %d overflows uint8", e.Op, i, v)
	}
	return uint8(v), nil
}

func (e *ChangeEntry) Ino(i int) (Ino, error) {
	v, err := e.Uint64(i)
	return Ino(v), err
}

func (e *ChangeEntry) Bool(i int) (bool, error) {
	s, err := e.Str(i)
	if err != nil {
		return false, err
	}
	switch s {
	case "true":
		return true, nil
	case "false":
		return false, nil
	}
	return false, fmt.Errorf("%s: argument %d %q is not a boolean", e.Op, i, s)
}

// ResultUint64 returns the i-th value after the ':' separator.
func (e *ChangeEntry) ResultUint64(i int) (uint64, error) {
	if i < 0 || i >= len(e.Result) {
		return 0, fmt.Errorf("%s: result %d out of range (%d)", e.Op, i, len(e.Result))
	}
	v, err := strconv.ParseUint(e.Result[i], 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%s: result %d %q is not an unsigned integer", e.Op, i, e.Result[i])
	}
	return v, nil
}

func (e *ChangeEntry) ResultIno(i int) (Ino, error) {
	v, err := e.ResultUint64(i)
	return Ino(v), err
}

func splitAndDecode(s string) ([]string, error) {
	if s == "" {
		return nil, nil
	}
	parts := strings.Split(s, ",")
	for i, p := range parts {
		v, err := logDecode(p)
		if err != nil {
			return nil, err
		}
		parts[i] = string(v)
	}
	return parts, nil
}

func parseSidTxn(s string) (sid, txnId uint64, err error) {
	comma := strings.IndexByte(s, ',')
	if comma < 0 {
		return 0, 0, fmt.Errorf("invalid %q", s)
	}
	if sid, err = strconv.ParseUint(s[:comma], 10, 64); err != nil {
		return 0, 0, err
	}
	txnId, err = strconv.ParseUint(s[comma+1:], 10, 64)
	return sid, txnId, err
}

func isChangelogOpName(op string) bool {
	if op == "" {
		return false
	}
	for i := 0; i < len(op); i++ {
		if c := op[i]; (c < 'A' || c > 'Z') && c != '_' {
			return false
		}
	}
	return true
}
