name: 'Load Action'
description: 'Juicefs load action'
inputs:
  meta_url:  
    description: 'meta url'
    required: true
    default: ''
  load_file:  
    description: 'path of the file to load'
    required: true
    default: ''
  
runs:
  using: "composite"
  steps:
    - name: Build linux target
      run: |
        make juicefs 
      shell: bash

    - name: Test
      run: |
        mount_point=/tmp/juicefs-load-test
        meta_url=${{inputs.meta_url}}
        load_file=${{inputs.load_file}}
        echo meta_url is: $meta_url
        db_name=$(basename $meta_url | awk -F? '{print $1}')
        if [[ "$meta_url" == mysql* ]]; then
          mysql -uroot -proot -h 127.0.0.1 -e "drop database if exists $db_name; create database $db_name;" 
        elif [[ "$meta_url" == postgres* ]]; then
          export PGPASSWORD="postgres"
          printf "\set AUTOCOMMIT on\ndrop database if exists $db_name; create database $db_name; " |  psql -U postgres -h localhost
        fi
        echo `date`, start load
        sudo ./juicefs load $meta_url $load_file
        echo `date`, finish load
        echo `date`, start dump
        sudo ./juicefs dump $meta_url dump.json
        echo `date`, finish dump
        sudo ./juicefs mount $meta_url $mount_point -d

      shell: bash