name: 'Load Action'
description: 'Juicefs load action'
inputs:
  meta_url:  
    description: 'meta url'
    required: true
    default: ''
  load_file:  
    description: 'path of the file to load'
    required: true
    default: ''
  
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.x'

    - name: Build linux target
      run: |
        make juicefs 
      shell: bash

    - name: Test
      run: |
        mount_point=/tmp/juicefs-load-test
        meta_url=${{inputs.meta_url}}
        load_file=${{inputs.load_file}}
        echo meta_url is: $meta_url
        db_name=$(basename $meta_url | awk -F? '{print $1}')
        if [[ "$meta_url" == mysql* ]]; then
          user=$(echo $meta_url |  awk -F/ '{print $3}' | awk -F@ '{print $1}' | awk -F: '{print $1}')
          password=$(echo $meta_url |  awk -F/ '{print $3}' | awk -F@ '{print $1}' | awk -F: '{print $2}')
          test -n "$password" && password="-p$password" || password=""
          host=$(basename $(dirname $meta_url) | awk -F@ '{print $2}'| sed 's/(//g' | sed 's/)//g' | awk -F: '{print $1}')
          port=$(basename $(dirname $meta_url) | awk -F@ '{print $2}'| sed 's/(//g' | sed 's/)//g' | awk -F: '{print $2}')
          test -z "$port" && port="3306" 
          mysql -u$user $password -h $host -P $port -e "drop database if exists $db_name; create database $db_name;" 
        elif [[ "$meta_url" == postgres* ]]; then
          export PGPASSWORD="postgres"
          printf "\set AUTOCOMMIT on\ndrop database if exists $db_name; create database $db_name; " |  psql -U postgres -h localhost
          printf "\set AUTOCOMMIT on\nALTER DATABASE $db_name SET DEFAULT_TRANSACTION_ISOLATION TO '$isolation_level';" |  psql -U postgres -h localhost
        fi
        echo `date`, start load
        sudo ./juicefs load $meta_url $load_file
        echo `date`, finish load
        echo `date`, start dump
        sudo ./juicefs dump $meta_url dump.json
        echo `date`, finish dump
        sudo ./juicefs mount $meta_url $mount_point -d

      shell: bash

    - name: log
      if: ${{ always() }}
      shell: bash
      run: | 
        tail -300 /var/log/juicefs.log
        grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true