name: 'Load Action'
description: 'Juicefs load action'
inputs:
  meta_url1:  
    description: 'meta url to dump'
    required: true
    default: ''
  meta_url2:  
    description: 'meta url to load'
    required: true
    default: ''
  files:  
    description: 'file count to load'
    required: true
    default: 5000000
  
runs:
  using: "composite"
  steps:
    - name: Build linux target
      run: |
        make juicefs 
      shell: bash

    - name: Test
      run: |
        meta_url1=${{inputs.meta_url1}}
        meta_url2=${{inputs.meta_url2}}
        echo meta_url1 is: $meta_url1, meta_url2 is: $meta_url2
        db_name1=$(basename $meta_url1 | awk -F? '{print $1}')
        db_name2=$(basename $meta_url2 | awk -F? '{print $1}')
        if [[ "$meta_url1" == mysql* ]]; then
          mysql -uroot -proot -h 127.0.0.1 -e "drop database if exists $db_name1; create database $db_name1;" 
          mysql -uroot -proot -h 127.0.0.1 -e "drop database if exists $db_name2; create database $db_name2;" 
        elif [[ "$meta_url1" == postgres* ]]; then
          export PGPASSWORD="postgres"
          printf "\set AUTOCOMMIT on\ndrop database if exists $db_name1; create database $db_name1; " |  psql -U postgres -h localhost
          printf "\set AUTOCOMMIT on\ndrop database if exists $db_name2; create database $db_name2; " |  psql -U postgres -h localhost
        fi
        ./juicefs format $meta_url1 load-test --trash-days 0
        dir_name=test 
        echo `date`: "start mdtest..."
        total_files=${{inputs.files}}
        files=$(expr $total_files/1110/50 | bc)
        ./juicefs mdtest $meta_url1 $dir_name --dirs 10 --depth 3 --files $files   --threads 50 --write 0
        echo `date`: "finish mdtest"
        echo `date`: "start dump..."
        ./juicefs dump $meta_url1 dump.json
        echo `date`: "finish dump"
        echo `date`: "start load..."
        ./juicefs load $meta_url2 dump.json
        echo `date`: "finish load"
        ./juicefs mount -d $meta_url1 /tmp/load-test-1
        ./juicefs mount -d $meta_url2 /tmp/load-test-2
        echo `date`: "start diff..."
        diff -ur /tmp/load-test-1/$dir_name /tmp/load-test-2/$dir_name 
        echo `date`: "finish diff"
      shell: bash