name: "aitests"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'main'
      - 'release-*'
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  aitests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: |
          make juicefs


      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format  redis://127.0.0.1:6379/1 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /jfs/ --enable-xattr --no-usage-report &
          python --version


      - name: SetUp Conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 2.7


      - name: Install Dependency
        run: |
          conda --version
          python --version
          conda install tensorflow=1.12.0
          sudo apt-get install libhdf5-dev
          pip install h5py


      - name: AI Test
        run: |
          stat /jfs/
          cd /jfs/
          git clone https://github.com/potterhsu/SVHNClassifier
          cd SVHNClassifier
          mkdir data
          cd data
          wget -O train.tar.gz http://ufldl.stanford.edu/housenumbers/train.tar.gz
          wget -O test.tar.gz http://ufldl.stanford.edu/housenumbers/test.tar.gz
          wget -O extra.tar.gz http://ufldl.stanford.edu/housenumbers/extra.tar.gz
          ls -lah
          echo "11111"
          time tar -zxvf train.tar.gz
          echo "22222"
          time tar -zxvf test.tar.gz
          echo "33333"
          time tar -zxvf extra.tar.gz
          cd ..
          time python convert_to_tfrecords.py --data_dir ./data



      - name: Fstests
        run: |
          echo "222"



      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  

      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
