name: "elastictest"


on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches: [ main ]
    paths-ignore:
      - 'docs/**'


jobs:
  elastictest_cleanlog_http:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: make juicefs

      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format redis://127.0.0.1:6379/1 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /data/jfs &


      - name: Esrally
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          echo "export http_proxy=http://proxy.acme.org:8888/" >>~/.bash_profile
          source ~/.bash_profile
          echo $http_proxy
          sudo pip3 install esrally
          sudo apt-get install pbzip2
          sudo chmod  777 /data/jfs/
          esrally race --track=geopoint  --car-params="data_paths:'/data/jfs'" &
          for i in {1..20}; do sleep 5m;echo "num $i";cat ~/.rally/logs/rally.log;done