name: "format-test"

on:
  push:
    branches:
      # - 'main'
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      # - 'main'
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  
jobs:
  format-test:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Build linux target
        run: make juicefs

      - name: Install Tools
        run: | 
          sudo apt install redis-tools
          
      - name: Test mount process exit on reformat
        run: |
          for i in {1..10}; do 
            echo "round $i"
            meta=redis://localhost/1
            ./juicefs format $meta volume-$i
            for j in {1..10}; do
              ./juicefs mount -d $meta /tmp/myjfs$i_$j
              cd /tmp/myjfs$i_$j
              bash -c 'for k in {1..300}; do echo abc>$k; sleep 0.2; done' || true & 
              cd -
            done
            sleep 3
            uuid=$(./juicefs status $meta | grep UUID | cut -d '"' -f 4) 
            ./juicefs destroy --force $meta $uuid
            ./juicefs format $meta new-volume-$i 
            sleep 15   
            ps -ef | grep juicefs
            pidof juicefs && exit 1
            uuid=$(./juicefs status $meta | grep UUID | cut -d '"' -f 4) 
            ./juicefs destroy --force $meta $uuid
          done

      - name: log
        if: ${{ always() }}
        run: | 
          cat ~/.juicefs/juicefs.log
          grep -v "UUID changed"  ~/.juicefs/juicefs.log | grep "<FATAL>:"  && exit 1 || true

      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"          

      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
