name: "gateway-random"

on:
  push:
    branches:
      - 'main'
      - 'release-**'
    paths:
      - '**/gateway-random.yml'
      - '**/gateway-random.sh'
      - '.github/scripts/hypo/s3**.py'
  pull_request:
    branches:
      - 'main'
      - 'release-**'
    paths:
      - '**/gateway-random.yml'
      - '**/gateway-random.sh'
      - '.github/scripts/hypo/s3**.py'
  schedule:
    - cron:  '0 19 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

jobs:
  build-matrix:
    runs-on: ubuntu-20.04
    steps:
      - id: set-matrix
        run: |
          echo "github.event_name is ${{github.event_name}}"
          echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"
          if [[ "${{github.event_name}}" == "schedule" || "${{github.event_name}}" == "workflow_dispatch" ]]; then
            echo 'meta_matrix=["mysql", "redis", "tikv"]' >> $GITHUB_OUTPUT
          else
            echo 'meta_matrix=["redis"]' >> $GITHUB_OUTPUT
          fi
    outputs:
      meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}

  gateway-random:
    timeout-minutes: 90
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set Variable
        id: vars
        run: |
          if [ "${{matrix.meta}}" == "fdb" ]; then
            echo "target=juicefs.fdb" >> $GITHUB_OUTPUT
          else
            echo "target=juicefs" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: ./.github/actions/build
        with: 
          target: ${{steps.vars.outputs.target}}

      - name: Test with example
        run: |
          if [[ ${{matrix.meta}} == "tikv" ]]; then
            subdir=true
          else
            subdir=false
          fi
          sudo -E SUBDIR=$subdir .github/scripts/command/gateway-random.sh test_run_example
          
      - name: Download example database
        timeout-minutes: 5
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: hypothesis-example-db-${{ matrix.meta }}
          path: .hypothesis/examples

      - name: Test randomly
        continue-on-error: true
        timeout-minutes: 60
        run: |
          if [[ ${{matrix.meta}} == "tikv" ]]; then
            subdir=true
          else
            subdir=false
          fi
          sudo -E LOG_LEVEL=WARNING SUBDIR=$subdir .github/scripts/command/gateway-random.sh test_run_all 2>&1 | tee fsrand.log
      
      - name: check fsrand.log
        if: always()
        run: | 
          grep "AssertionError" fsrand.log && exit 1 || true

      - name: Upload example database
        uses: actions/upload-artifact@v4
        if: always()
        with:
          include-hidden-files: true
          name: hypothesis-example-db-${{ matrix.meta }}
          path: .hypothesis/examples

      - name: check log
        if: always()
        run: | 
          if [ -f /var/log/juicefs-gateway.log ]; then
            tail -300 /var/log/juicefs-gateway.log
            grep "<FATAL>:" /var/log/juicefs-gateway.log && exit 1 || true
          fi
          
      - name: Setup upterm session
        if: failure() && (github.event.inputs.debug == 'true' || github.run_attempt != 1)
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1

  success-all-test:
    runs-on: ubuntu-latest
    needs: [gateway-random]
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3

      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1

      - name: Send Slack Notification
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"

      - name: Success
        if: success() 
        run: echo "All Done"