name: "mongodb_mmap"

on:
  push:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  mongodb_mmap:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
          architecture: 'x64'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: |
          make juicefs


      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format --trash-days 0 redis://127.0.0.1:6379/1 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /jfs/ --enable-xattr --cache-size 3072 --no-usage-report &



      - name: Set up Mongodb
        run: |
          df -lh
          cd /jfs/
          git clone https://github.com/sanwan/actionsoftware.git
          cd actionsoftware
          tar zxvf mongodb-linux-x86_64-3.0.0.tgz
          cd mongodb-linux-x86_64-3.0.0
          mkdir /jfs/mongodb/
          nohup ./bin/mongod --dbpath /jfs/mongodb &



      - name: Insert Data
        run: |
          df -lh
          cd /jfs/
          wget -O ycsb.tar.gz -q https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0/ycsb-0.5.0.tar.gz
          tar -zxvf ycsb.tar.gz
          cd ycsb-0.5.0
          sed -i "s?recordcount=1000?recordcount=1000000?" workloads/workloadf
          sed -i "s?operationcount=1000?operationcount=15000?" workloads/workloadf
          cat workloads/workloadf
          time ./bin/ycsb load mongodb -s -P workloads/workloadf  -threads 10 > outputLoad.txt
          df -lh


      - name: Read Modify and Write
        run: |
          df -lh
          cd /jfs/ycsb-0.5.0/
          ps -aux | grep mongo
          echo "run read modify write"
          time ./bin/ycsb run mongodb -s -P workloads/workloadf -threads 10 > outputRun.txt
          df -lh

      - name: Log
        if: ${{ always() }}
        run: |
          echo "juicefs log"
          sudo tail -n 1000 /var/log/juicefs.log
          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true

      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  

      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
