name: "tpch_clickhouse"

on:
  push:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron:  '30 20 * * *'

  workflow_dispatch:

jobs:
  tpchch-noraml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/clickhouse
        with:
          type: normal

  tpchch-limitcache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/clickhouse
        with:
          type: limitcache

  tpchch-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/clickhouse
        with:
          type: local