apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "juicefs-s3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret }}
  name: {{ .name | b64enc | quote }}
  metaurl: {{ .metaurl | b64enc | quote }}
  {{- if .storage }}
  storage: {{ .storage | b64enc | quote }}
  {{- end }}
  {{- if .accessKey }}
  access-key: {{ .accessKey | b64enc | quote }}
  {{- end }}
  {{- if .secretKey }}
  secret-key: {{ .secretKey | b64enc | quote }}
  {{- end }}
  {{- if .bucket }}
  bucket: {{ .bucket | b64enc | quote }}
  {{- end }}
  {{- end }}
